version: "3.3"

services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./shared/projects:/var/www
    depends_on:
      - mysql
      - redis      
    networks:
      - mysql
      - redis
      - nginx       

  php-cli:
    build: "./php-cli"
    volumes:
      - "./shared/projects:/var/www"
    depends_on:
      - mysql
      - redis  
    networks:
      - mysql 
      - redis

  mysql:
     build: ./mysql
     volumes: 
       - ./shared/mysql/data:/var/lib/mysql
     networks:
       - mysql
     ports:
       - 3306:3306

  redis:
     build: ./redis
     volumes:
       - ./shared/redis/data:/data
       - ./shared/redis/conf:/usr/local/etc/redis
     networks:
       - redis

  nginx:
     build: ./nginx
     volumes:
       - ./shared/projects:/data/www
       - ./shared/nginx/logs:/var/log/nginx
       - ./shared/nginx/conf:/etc/nginx/conf.d
     ports:
       - ${WEB_PORT_MAP_80}:80
       - ${WEB_PORT_MAP_8080}:8080
     depends_on:
       - php-fpm
     networks:
       - nginx

networks:
  mysql:
  redis:  
  nginx: